theme: jekyll-theme-hacker
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: katex
  syntax_highlighter: rouge

